### ISSUE TITLE
Dependancy error running container manageiq/httpd_configmap_generator:latest

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/httpd_configmap_generator#55]
How to reproduce
```
docker run -d  --privileged manageiq/httpd_configmap_generator:latest
CONFIGMAP_GENERATOR_ID="`docker ps -l -q`"
docker exec -it $CONFIGMAP_GENERATOR_ID /bin/bash -i

[root@db919d051ca1 httpd]# httpd_configmap_generator ipa
```

Running the httpd_configmap_generator always gives a  error
```
Could not find gem 'codeclimate-test-reporter (~> 1.0.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

**Comment by dermilchbub** [comment]
I have the same issue. 
Overall this generator is very frustrating. Is there no option to edit an example file? 
Kind Regards

**Comment by Fryguy** [comment]
> Is there no option to edit an example file?

That is why this CLI was written in the first place.  Setup of anything auth related is ridiculously complicated if done manually.  The goal here was to create a simpler CLI where you can just enter the values you care about and it will spit out all of the files you'll need for auth.  It was originally designed to spit out kubernetes config maps because those same config maps were meant to be mounted with our httpd-init container.  That part of the design probably needs to be updated.
